language: android
jdk: oraclejdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-19
    - sys-img-armeabi-v7a-android-19
sudo: required
before_install:
  - chmod +x travis/before_install.sh
  - ./travis/before_install.sh
